name: alsf-rrp
channels:
  - bioconda
  - conda-forge
dependencies:
  - fastp=1.0.1=hee05c9d_0
  - isa-l=2.31.1=h5505292_1
  - libcxx=21.1.5=hf598326_0
  - libdeflate=1.22=hd74edd7_0
prefix: /Users/teaching/miniforge3/envs/alsf-rrp
